config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'

  devise_for :users
  resources :books do
      resources :comments
  end
  root 'books#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one :currency
  has_one :language
  has_one :genre
  has_many :comments

  mount_uploaders :photos, PhotoUploader
  serialize :photos, JSON # If you use SQLite, add this line.

  validates :title, :price, :description, :year, :pages, :author, presence: true
  validates :price, :year, :pages, numericality: { only_integer: true, message: "only allows numericality" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/currency.rb
class Currency < ApplicationRecord
    belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
      belongs_to :book
end

app/models/language.rb
class Language < ApplicationRecord
      belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_book, only: [:show, :edit, :update, :destroy]
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_param)
    if @book.save
      flash[:notice] = "Successfully created"
      redirect_to book_path(@book.id)
    else
      flash[:error] = "Has error with created"
      render 'new'
    end
  end

  def show
    @comments = @book.comments
  end

  def edit
  end

  def update
    if @book.update(book_param)
      flash[:notice] = "Successfully updated"
      redirect_to book_path(@book.id)
    else
      flash[:error] = "Has error with created"
      render 'edit'
    end
  end

  def destroy
    @book.destroy
    redirect_to root_path
  end
private
  def book_param
    params.require(:book).permit(:user_id, :title, :description, :price, :currency_id, :genre_id, :language_id, :author, :year, :pages, {photos: []})
  end

  def find_book
   @book = Book.find_by(id: params[:id])
 end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
before_action :set_book

  def new
    @comment = Comment.new
  end

  def create
    params[:comment][:user_id] = current_user.id
    params[:comment][:book_id] = @book.id
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to book_path(@book.id)
    else
      render 'new'
    end

  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

private
  def set_book
    @book = Book.find_by(id: params[:book_id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :book_id, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/books/edit.html.erb
<h1>Edit <%= @book.title %></h1>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book, url: {action: "update"} do |f| %>
  <strong>Book title</strong><br>
    <%= f.text_field :title %><br />
  <strong>Book description</strong><br>
    <%= f.text_area :description, size: "60x12" %><br />
  <strong>Price</strong><br>
    <%= f.text_field :price %>
    <%= f.select :currency_id  , Currency.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a type of currency'%> <br>

    <%= f.select :genre_id  , Genre.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a genre'%> <br>

    <%= f.select :language_id  , Language.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a book language'%> <br>

  <strong>Book author</strong> <br>
      <%= f.text_field :author %><br />
  <strong>Year of publication</strong><br>
      <%= f.text_field :year %><br />
  <strong>Pages</strong><br>
      <%= f.text_field :pages %><br /> <br>
  <%= f.submit "Update" %>
<% end %>

app/views/books/index.html.erb
<h1>BookSH</h1>
<% if @books == [] %>
  <p>NO books</p>
<% else %>
  <% @books.each do |book| %>
    <hr>
    <%= link_to image_tag(book.photos[0].url, size: "300x500"), book_path(book.id) %>  	<br>
    <%= link_to book.title, book_path(book.id) %><br>
    <h3><%= book.author %></h3><br>
    <strong>Price: </strong>
    <%= book.price %>
    <%= Currency.find_by(id: book.currency_id).try(:title) %> <br>
   	<hr>
  <% end %>
<% end %>

app/views/books/new.html.erb
<h1>Add new book</h1>
<%= form_for @book, url: {action: "create"} do |f| %>

<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <strong>Book title</strong><br>
    <%= f.text_field :title %><br />
  <strong>Book description</strong><br>
    <%= f.text_area :description, size: "60x12" %><br />
  <strong>Price</strong><br>
    <%= f.text_field :price %>
    <%= f.select :currency_id  , Currency.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a type of currency'%> <br>

    <%= f.select :genre_id  , Genre.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a genre'%> <br>

    <%= f.select :language_id  , Language.all.collect {|p| [ p.title, p.id ]}, :prompt => 'Choose a book language'%> <br>

  <strong>Book author</strong> <br>
      <%= f.text_field :author %><br />
  <strong>Year of publication</strong><br>
      <%= f.text_field :year %><br />
  <strong>Pages</strong><br>
      <%= f.text_field :pages %><br />
  <strong>Add photos</strong><br>
    <%= f.file_field :photos, multiple: true %><br><br>
  <%= f.submit "Create" %>
<% end %>

app/views/books/show.html.erb
<h1> «<%= @book.title %>» <%= @book.author %><br></h1>
<strong>Photos:</strong> <br>
	<% @book.photos.each do | photo | %>
		<%= image_tag(photo.url, size: "300x500")%>	<br> <br>
	<% end %>
  <strong>Price: <%= @book.price %> <%= Currency.find_by(id: @book.currency_id).try(:title) %> <br></strong> <br>
  <strong>Short description</strong> <br>
  <%= @book.description %> <br> <br>
<strong>Characteristic</strong><br>
Genre: <%= Genre.find_by(id: @book.genre_id).try(:title) %> <br>
Language: <%= Language.find_by(id: @book.language_id).try(:title) %><br>
Year: <%= @book.year %><br>
Pages: <%= @book.pages %><br>

<% if user_signed_in? %>
  <% if @book.user_id == current_user.id %>
  <hr>
  <%= link_to "Edit", edit_book_path %> |
  <%= link_to "Delete", book_path(@book.id), method: :delete %>
<% end %>

<% end %>

<p><%= link_to "Write Comment", new_book_comment_path(@book.id) %></p>

<% @comments.each do |comment| %>
   <p>
    User <b><%= comment.user.email.split("@").first %></b>: <br />
    <%= comment.body %><br />
   </p>
<% end %>

app/views/comments/new.html.erb
<h1>Write a comment</h1>
<%= form_for @comment, url: book_comments_path(@book.id) do |f| %>
<%= f.text_area :body, size: "60x12" %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/layouts/_footer.html.erb
<hr>
number +38(067) 265 73 23

app/views/layouts/_header.html.erb
<%= link_to 'Home',root_path, :class => 'navbar-link' %> | <%= link_to "Add new book", new_book_path, :class => 'navbar-link' %> ᅠ|  ᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠ
<% if user_signed_in? %>
  <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookSH</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>